# Config for grunt-jasmine-nodejs
# https://github.com/onury/grunt-jasmine-nodejs
{
    # task specific (default) options
    options: {
        specNameSuffix: 'spec.js', # also accepts an array
        helperNameSuffix: 'helper.js',
        useHelpers: false,
        # options for built-in reporters
        reporters: {
            # console (default) reporter
            console: {
                colors: true,
                verbose: true,
                cleanStack: true
            },
            junit: {
                savePath: './reports',
                filePrefix: 'junit-report',
                consolidate: true,
                useDotNotation: true
            },
            nunit: {
                savePath: './reports',
                filename: 'nunit-report.xml',
                reportName: 'Test Results'
            },
            teamcity: false,
            tap: false
        },
        # list of custom Jasmine reporter objects
        customReporters: []
    },
    all: {
        # target specific options
        options: {
            useHelpers: true
        },
        # spec files
        specs: [
            "test/**"
        ],
        helpers: [
            "test/helpers/**"
        ]
    }
}